Patch 1
bottlerocket-os/bottlerocket pull request #1107
Opened 2020-09-03 18:00 UTC by troyaws

**Issue number:**

https://github.com/bottlerocket-os/bottlerocket/issues/1106

**Description of changes:**

Updating BUILDING.md to articulate missing dependencies.

**Testing done:**

Executed a build following the instructions.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2020-09-03 23:16 UTC, bcressey commented on BUILDING.md
> +Error messages from the Rust tooling do not clearly identify the issues.
Let's not say this part since it can be read as criticizing tools or crates from the Rust ecosystem rather than anything that's Bottlerocket specific.
```suggestion
```

2020-09-03 23:16 UTC, bcressey commented on BUILDING.md
> +The build process artifacts and resulting images can consume in excess of 4GB in the local directory.
`System Requirements` might be a better heading, then we can add recommendations for storage + memory + compute.

Systems should have at least 80 GB of storage available. There's quite a lot of overhead from the intermediate Docker layers that are created.

2020-09-03 23:16 UTC, bcressey commented on BUILDING.md
> +- `build-essential`
Fedora doesn't have a direct equivalent to this. It might be better to split it into separate commands, with an Ubuntu example and a Fedora example.

2020-09-03 23:16 UTC, bcressey commented on BUILDING.md
> +#### Operating System Packages
Maybe call this "Linux" since it'll live at the same level as "Rust" and "Docker". Or we can fold it into the previous `System Requirements` section.

2020-09-03 23:16 UTC, bcressey commented on BUILDING.md
> +The Rust tooling requires certain operating system packages to be installed in order to complete builds.
```suggestion
The build system requires certain operating system packages to be installed.  
```

2020-09-04 11:44 UTC, troyaws reviewed
Updated per feedback.

2020-09-04 19:54 UTC, zmrow requested changes

2020-09-04 19:54 UTC, zmrow commented on BUILDING.md
> +The build process artifacts and resulting images can consume in excess of 4GB in the local directory.
Let's bump up this number quite a bit as @bcressey mentioned: we're probably safe to say around 80GB.

2020-09-04 20:11 UTC, troyaws reviewed
Disk space requirement updated.

2020-09-14 16:10 UTC, zmrow reviewed
Let's squash the commits into a single commit and I'm good to approve! :+1:

2020-09-15 17:55 UTC, zmrow approved these changes
LGTM!

I'll squash the commits when I merge this

2020-09-15 18:22 UTC, merged