ecs-agent: update to 1.50.2
bottlerocket-os/bottlerocket pull request #1353
Opened 2021-02-24 23:27 UTC by arnaldo2792

**Issue number:**
N/A

**Description of changes:**
```
ecs-agent: update to 1.50.2
```
This PR is the continuation of #1340, and updates the `ecs-agent` to the latest release

**Testing done:**
- aws-ecs-1 x86_64/aarch64:
    - Internal ECS testing succeeded
    - Launched nginx task/service through the ECS console
    - Launched container from within the host
    - `systemctl status` looks good
    - `journalctl -p3 -xb` looks good

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2021-02-24 23:30 UTC, samuelkarp requested changes

2021-02-24 23:30 UTC, samuelkarp commented on packages/ecs-agent/ecs-agent.spec
>  %global gitrev e9b600d2
This needs to be updated too.

2021-02-24 23:48 UTC, arnaldo2792 commented on packages/ecs-agent/ecs-agent.spec
>  %global gitrev e9b600d2
Fixed

2021-02-24 23:50 UTC, samuelkarp approved these changes

2021-02-24 23:51 UTC, tjkirch approved these changes

2021-02-25 01:30 UTC, webern approved these changes
🎉

2021-02-25 01:32 UTC, merged