restart modified host containers
bottlerocket-os/bottlerocket pull request #1722
Opened 2021-08-24 00:47 UTC by gthao313

When a host container is running and its settings have changed,
bottlerocket will restart and apply new changes to this host container.

**Issue number:**
#1531

**Description of changes:**
If a host container is running, and its settings have changed, we should restart it so the settings take effect.

**Testing done:**
start a host-container and change some setting that might affect it like superpower, image URL, proxy....

### Control container

source: `apiclient set -j '{"host-containers": {"control": {"source": "328549459982.dkr.ecr.us-west-2.amazonaws.com/bottlerocket-control:v0.5.0"}}}'`

result:
```
"control":{"source":"328549459982.dkr.ecr.us-west-2.amazonaws.com/bottlerocket-control:v0.5.0"}}
```

```
Aug 23 23:50:49 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: host-containers@control.service: Succeeded.
Aug 23 23:50:49 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: Stopped Host container: control.
Aug 23 23:50:49 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: Started Host container: control.
Aug 23 23:50:49 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: Reloading.
Aug 23 23:50:49 ip-192-168-78-239.us-west-2.compute.internal host-ctr[19285]: time="2021-08-23T23:50:49Z" level=info msg="pulling with Amazon ECR Resolver" ref="ecr.aws/arn:aws:ecr:us-west-2:328549459982:repository/bottlerocket-control:v0.5.0"
Aug 23 23:50:52 ip-192-168-78-239.us-west-2.compute.internal host-ctr[19285]: time="2021-08-23T23:50:52Z" level=info msg="pulled image successfully" img="ecr.aws/arn:aws:ecr:us-west-2:328549459982:repository/bottlerocket-control:v0.5.0"
```

Superpower: `apiclient set -j '{"host-containers": {"control": {"superpowered": true}}}'`

result:
```
"control":{superpowered":true}}
```
```
Aug 23 23:56:04 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: host-containers@control.service: Succeeded.
Aug 23 23:56:04 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: Stopped Host container: control.
Aug 23 23:56:04 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: Started Host container: control.
Aug 23 23:56:04 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: Reloading.
Aug 23 23:56:04 ip-192-168-78-239.us-west-2.compute.internal host-ctr[21669]: time="2021-08-23T23:56:04Z" level=info msg="pulling with Amazon ECR Resolver" ref="ecr.aws/arn:aws:ecr:us-west-2:328549459982:repository/bottlerocket-control:v0.5.0"
```

user-data: TODO

### Admin container

source: `apiclient set -j '{"host-containers": {"admin": {"source": "328549459982.dkr.ecr.us-west-2.amazonaws.com/bottlerocket-admin:v0.7.1"}}}' `

result:
```
{"admin":{"source":"328549459982.dkr.ecr.us-west-2.amazonaws.com/bottlerocket-admin:v0.7.1"}}}
```

```
Aug 23 23:52:37 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: host-containers@admin.service: Succeeded.
Aug 23 23:52:37 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: Stopped Host container: admin.
Aug 23 23:52:37 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: Started Host container: admin.
Aug 23 23:52:37 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: Reloading.
Aug 23 23:52:37 ip-192-168-78-239.us-west-2.compute.internal host-ctr[20159]: time="2021-08-23T23:52:37Z" level=info msg="pulling with Amazon ECR Resolver" ref="ecr.aws/arn:aws:ecr:us-west-2:328549459982:repository/bottlerocket-admin:v0.7.1"
Aug 23 23:52:38 ip-192-168-78-239.us-west-2.compute.internal host-ctr[20159]: time="2021-08-23T23:52:38Z" level=info msg="pulled image successfully" img="ecr.aws/arn:aws:ecr:us-west-2:328549459982:repository/bottlerocket-admin:v0.7.1"
```

superpowered: When I set to false, I'll unable to access to sheltie. If anyway that I can check the log?
But when I set from false to true, Host-container restart

`apiclient set -j '{"host-containers": {"admin": {"superpowered": true}}}'`

result:
```
{"admin":{"superpowered":true}},
```
```
Aug 24 00:10:32 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: host-containers@admin.service: Succeeded.
Aug 24 00:10:32 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: Stopped Host container: admin.
Aug 24 00:10:32 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: Started Host container: admin.
Aug 24 00:10:32 ip-192-168-78-239.us-west-2.compute.internal systemd[1]: Reloading.
Aug 24 00:10:32 ip-192-168-78-239.us-west-2.compute.internal host-ctr[27616]: time="2021-08-24T00:10:32Z" level=info msg="pulling with Amazon ECR Resolver" ref="ecr.aws/arn:aws:ecr:us-west-2:328549459982:repository/bottlerocket-admin:v0.7.1"
```
user-data: TODO

### Proxy: TODO

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2021-08-30 17:40 UTC, gthao313 commented
Currently I have tested host-container settings and proxy setting which I think might affect host-container restart. If you think there are another more settings that would affect host-container restart, Please let me know! I would like to do more test. Thanks.

2021-09-10 20:30 UTC, zmrow approved these changes
:mushroom:

2021-09-10 23:53 UTC, webern approved these changes

2021-09-13 23:03 UTC, jpculp approved these changes

2021-09-14 18:51 UTC, arnaldo2792 requested changes

2021-09-14 18:51 UTC, arnaldo2792 commented on sources/api/host-containers/src/main.rs
> +        else if host_containerd_unit.is_active()? && systemd_unit.is_enabled()? {
I think this change should be done in a different part. For a  little context, we only want to enable host-containers'  units during the `multi-user.target` execution.

With your current approach, during the execution of `preconfigured.target`, and with user data as:

```toml
[settings.host-containers.control]
source  = "<an-image>"
```

This condition will be false:

```rust
host_containerd_unit.is_active()? && systemd_unit.is_enabled()?
```

And since we have this conditional:

```rust
match command(constants::SYSTEMCTL_BIN, &["get-default"])?.trim().as_ref() {
            "multi-user.target" => {
                debug!("Enabling and starting container: '{}'", unit_name);
                systemd_unit.enable_and_start()?
            }
            _ => {
                debug!("Enabling: '{}'", unit_name);
                systemd_unit.enable()?
            }
};
```

The unit will be just enabled, not started. Now, say you have a bootstrap container that changes the host-containers' settings, this new condition will now be true, since the unit was enabled during `preconfigured.target`:

```rust
host_containerd_unit.is_active()? && systemd_unit.is_enabled()?
```

Thus, your change effectively affects when host containers' units are started. I think a better approach is to modify the `enable_and_start` method, since it will only be executed when `multi-user.target` is the current target.

I think within that method, you should check if the unit is active with `self.active()?`, if it is, then you can run your method `try_reload_or_restart`. 

This will keep the consistency of only starting host container units in `multi-user.target`.

2021-09-15 23:53 UTC, gthao313 commented
Push above address @arnaldo2792 's comment which it should only affect containers in the multi-user.target.

2021-09-21 18:11 UTC, arnaldo2792 approved these changes
:hiking_boot:

2021-09-21 18:44 UTC, jpculp approved these changes
⛰️

2021-09-21 19:40 UTC, zmrow approved these changes
:paintbrush:

2021-09-21 20:06 UTC, webern approved these changes

2021-09-21 21:02 UTC, merged