update rust dependencies
bottlerocket-os/bottlerocket pull request #2019
Opened 2022-03-23 17:59 UTC by webern

**Issue number:**

Closes #1965

**Description of changes:**

Update rust dependencies.

**Testing done:**

In progress.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2022-03-23 20:38 UTC, etungsten approved these changes

2022-03-24 15:00 UTC, zmrow approved these changes
:lobster:

2022-03-24 17:03 UTC, jpculp requested changes
Should the "sources: update hyper to 0.11.10" commit be **reqwest** instead?

2022-03-24 17:05 UTC, webern commented
^ rebase and fix commit message typo

2022-03-24 17:13 UTC, jpculp approved these changes

2022-03-24 20:37 UTC, merged