Docs: Adds nvidia ecs variant to README
bottlerocket-os/bottlerocket pull request #2244
Opened 2022-06-24 22:19 UTC by stockholmux

Signed-off-by: Kyle J. Davis <kyledvs@amazon.com>

**Issue number:** n/a

**Description of changes:** Adds ecs nvidia variant to the readme 

**Testing done:** eyeballs only

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2022-06-24 22:21 UTC, etungsten approved these changes

2022-06-24 23:08 UTC, bcressey approved these changes

2022-06-24 23:14 UTC, arnaldo2792 approved these changes

2022-06-24 23:16 UTC, arnaldo2792 requested changes, later dismissed

2022-06-24 23:16 UTC, arnaldo2792 commented on README.md
>  The following variant supports ECS:
```suggestion
The following variants supports ECS:
```

2022-06-27 16:07 UTC, bcressey reviewed
Can you rebase locally to squash the commits together?

2022-06-27 16:07 UTC, bcressey commented on README.md
> +The following variants supports ECS:
```suggestion
The following variants support ECS:
```

2022-06-28 16:10 UTC, stockholmux commented
@bcressey Done. 
@arnaldo2792 Can you re-review to unblock merging?

2022-06-28 23:47 UTC, bcressey approved these changes

2022-06-29 02:17 UTC, arnaldo2792 approved these changes

2022-06-29 13:18 UTC, merged