host-ctr: add a mount for system logs
bottlerocket-os/bottlerocket pull request #2295
Opened 2022-07-22 18:43 UTC by mchaker

**Issue number:**

#2196 

**Description of changes:**

Add a container-visible mount for /var/log/support,
which contains system logs.

**Testing done:**

- [x] booted an `aws-dev` container and checked that both the control and admin containers could see `/.bottlerocket/rootfs/var/log/support/`

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2022-07-22 19:28 UTC, mchaker commented
_Latest force push: added a mention of the log visibility in the README._

2022-07-22 19:39 UTC, arnaldo2792 requested changes

2022-07-22 19:39 UTC, arnaldo2792 commented on README.md
> +Log archives are also visible to host containers.
Nit: move this line a few lines above, before "You can use SSH", and say something like:

```
This archive is accessible from host containers at `<blah>`.
....
```

2022-07-22 19:46 UTC, mchaker commented
_Latest force push: revise README documentation_

2022-07-22 21:56 UTC, bcressey requested changes
This needs to go under a separate directory for the purpose, like  `/.bottlerocket/support`. `rootfs` is a different directory with a different purpose - exposing the host's entire root filesystem.

2022-07-22 22:16 UTC, mchaker commented
_Latest force push: change mount destination directory to align with directory purposes_

2022-07-25 22:14 UTC, bcressey commented on README.md
> +This archive is accessible from host containers at `/.bottlerocket/support`.
You can also fix the URL in the code block below to reflect this path.

2022-07-25 22:26 UTC, mchaker commented
_Latest force push: fix sample SSH command referencing the new log mount path_

2022-07-26 02:57 UTC, bcressey approved these changes

2022-07-27 00:27 UTC, arnaldo2792 approved these changes

2022-07-27 01:09 UTC, merged