Remove kubernetes 1.20 variants
bottlerocket-os/bottlerocket pull request #2421
Opened 2022-09-15 16:49 UTC by jpmcb

**Issue number:**

Closes #2400

**Description of changes:**

```
- Remove aws-k8s-1.20 variant
- Remove vmware-k8s-1.20 variant

Signed-off-by: John McBride <jpmmcb@amazon.com>
```

**Testing done:**

`cargo make check && cargo make build` 👍🏼 

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2022-09-15 16:51 UTC, jpmcb commented
Marking this draft until we're abit closer to the November timeline (when EKS support for k8s 1.20 will drop per the issue noted above)

2022-10-18 17:58 UTC, jpmcb commented
Ready for review now and will target the `1.11.0` release

2022-10-18 21:22 UTC, etungsten requested changes
We should delete `models/src/aws-k8s-1.20` like in https://github.com/bottlerocket-os/bottlerocket/pull/2316/files#.

2022-10-18 21:22 UTC, etungsten commented on PUBLISHING-VMWARE.md
> +cargo make -e BUILDSYS_VARIANT=vmware-k8s-1.21 upload-ova
Let's move this to the latest.
```suggestion
cargo make -e BUILDSYS_VARIANT=vmware-k8s-1.24 upload-ova
```

2022-10-19 14:41 UTC, jpmcb commented
Force pushed to also remove `sources/models/src/aws-k8s-1.20` and `sources/models/src/vmware-k8s-1.20`. Updated `PUBLISHING-VMWARE.md` to indicate using 1.24 kubernetes

2022-10-19 16:13 UTC, webern approved these changes
I'm not sure the best way to make sure nothing is missed when reviewing this type of PR. I did compare it to https://github.com/bottlerocket-os/bottlerocket/pull/2316 though and didn't surface any issues.

2022-10-19 16:14 UTC, etungsten approved these changes

2022-10-19 20:30 UTC, bcressey approved these changes

2022-10-19 20:30 UTC, bcressey commented on README.md
> -* `vmware-k8s-1.20`
Traditionally we add the removed variants to the "The following variants are no longer supported" section below.

2022-10-19 22:25 UTC, jpmcb commented
Force pushed to address Ben's comment: Added `aws-k8s-1.20` and `vmware-k8s-1.20` to the "The following variants are no longer supported" section. Will merge with passing tests.

2022-10-20 04:33 UTC, bcressey approved these changes

2022-10-20 12:18 UTC, stmcginnis approved these changes
<img width="132" alt="image" src="https://user-images.githubusercontent.com/3922475/196946242-72c6d4c5-de2a-4961-939d-990969f67b8d.png">

🥇

2022-10-20 15:01 UTC, merged