testsys: Provide advanced config control
bottlerocket-os/bottlerocket pull request #2799
Opened 2023-02-11 00:07 UTC by ecpullen

**Issue number:**

N/A

**Description of changes:**

When developing TestSys, the simplicity of `cargo make test` calls can make it difficult to force certain behavior to occur. It is also possible that the default values are not the best for a user. This pr introduces `DeveloperConfig` for additional control.

`DeveloperConfig` is intended to contain advanced configuration values that most users shouldn't need to care about. There is currently a 1:1 mapping for `GenericVariantConfig : Command Line Env Variables` that I'd like to preserve which is why I created a new type.

Currently there are 4 configuration values:
* `cluster-destruction-policy` allows users to control the destruction policy of cluster crds. The defaults currently used were carefully selected to improve the ux, but some users may want to alter this behavior
* `bottlerocket-destruction-policy` allows users to control the destruction policy of Bottlerocket crds.
* `keep-tests-running` is used to set the `keep_running` field on tests. With `keep_running: true`, the test's pods are kept in a running state until the test is deleted, as a result, the default behavior has been set to `false`, but can be enabled if a user wishes to.
* `image-account-id` is used to set an alternate account as the one starting AMIs are stored in. This is useful for storing AMIs in a separate account from the one testing is occurring in. Without `image-account-id`, a user needs to find the ami id from the account and set `TESTSYS_STARTING_IMAGE_ID`. With this new variable, all manual steps are removed.

**Testing done:**

Tested each new value and verified that the expected values were added to the CRDs.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2023-02-12 12:26 UTC, stmcginnis requested changes
Can we get a small section added to `TESTING.md` that documents this?

2023-02-13 17:58 UTC, ecpullen commented
> Can we get a small section added to `TESTING.md` that documents this?

The `dev` configurations were purposely left out of `TESTING.md` to keep it from getting too long and keep it simple. I prefer to keep these configuration values documented in the code base instead to prevent accidental usage.

2023-02-13 22:00 UTC, etungsten approved these changes

2023-02-13 22:30 UTC, stmcginnis approved these changes
I would prefer to see some documentation somewhere other than the code, but makes sense. Everything else looks good to me.

2023-02-13 22:40 UTC, ecpullen commented
Added a note in `Test.toml.example` for the new fields.

2023-02-13 22:41 UTC, stmcginnis approved these changes
Awesome, thanks @ecpullen!

2023-02-14 18:34 UTC, merged