Update rust dependencies
bottlerocket-os/bottlerocket pull request #3149
Opened 2023-05-26 00:59 UTC by jpculp

**Description of changes:**

Ran `cargo update` for `sources` and `tools`, avoided some updates that pull unnecessary extra versions, and adjusted the deny TOMLs as necessary. Also included updates for **AWS SDK for Rust**, `coldsnap`, and `tough`.

**Testing done:**

_Coming soon!_

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2023-05-26 01:01 UTC, jpculp commented
`coldsnap` and `tough` are temporarily pointing to my forks until their next release. Until then we'll keep this in draft.

2023-06-06 22:44 UTC, jpculp commented
Added a temporary commit to fix some hashes and bump some crates.

2023-06-09 19:27 UTC, webern requested changes
Looks good other than the temporary github references.

2023-06-09 19:27 UTC, webern commented on sources/api/migration/migrator/Cargo.toml
> +tough = { git = "https://github.com/jpculp/tough", branch="update-rust-deps", version="0.13" }
reminder

2023-08-04 23:07 UTC, jpculp commented
Superseded by #3330.

2023-08-04 23:07 UTC, closed without merging