[1.15.x] Cherry picks of recent updates from `develop`
bottlerocket-os/bottlerocket pull request #3502
Opened 2023-10-03 21:58 UTC by stmcginnis

**Description of changes:**

This is a set of cherry picks from the `develop` branch to `1.15.x` to prepare for a future 1.15.1 release.

This includes the commits from the following PRs:

- #3439 
- #3491 
- #3499 
- #3498 
- #3500 
- #3501

**Testing done:**

See testing performed on `develop` for each change.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2023-10-03 22:01 UTC, yeazelm approved these changes

2023-10-04 14:11 UTC, webern requested changes
You're going to need a twoliter update that isn't merged yet for testsys fixes.

2023-10-04 14:20 UTC, stmcginnis commented
> You're going to need a twoliter update that isn't merged yet for testsys fixes.

That was going to be done in a follow up along with getting the CHANGELOG and Release.toml updates. But we can wait and just do it all in one go too.

2023-10-04 18:00 UTC, webern approved these changes
Changing to approve since team is aware of the need for a Twoliter (testsys) update.

2023-10-04 20:55 UTC, arnaldo2792 approved these changes

2023-10-04 21:50 UTC, merged