CHANGELOG: add changelog for 1.17.0
bottlerocket-os/bottlerocket pull request #3648
Opened 2023-12-07 22:31 UTC by sam-berning

**Description of changes:**

CHANGELOG for 1.17.0

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2023-12-07 22:48 UTC, etungsten commented on CHANGELOG.md
> +## OS Changes
Missing #3642 - 3rd party package updates. We also bumped containerd and runc in #3612

2023-12-07 22:48 UTC, jpculp requested changes

2023-12-07 22:48 UTC, jpculp commented on CHANGELOG.md
> +* Update kernel to 5.10.199, 5.15.137, 6.1.61 ([#3611])
Looks like we bumped the kernels twice.
```suggestion
* Update kernel to 5.10.201, 5.15.139, 6.1.61 ([#3611],[#3643])
```

2023-12-07 23:16 UTC, sam-berning commented
updated to adopt @etungsten and @jpculp's suggestions

2023-12-07 23:36 UTC, jpculp approved these changes

2023-12-08 00:07 UTC, etungsten approved these changes

2023-12-08 21:45 UTC, etungsten approved these changes

2023-12-08 21:51 UTC, rpkelly approved these changes

2023-12-08 22:08 UTC, merged