host-containers: migrate to use config file
bottlerocket-os/bottlerocket pull request #3777
Opened 2024-02-14 19:37 UTC by sam-berning

**Issue number:**

Closes #3627 

**Description of changes:**

Removes dependency on the API model from host-containers by changing it to use a config file rendered from the settings.

**Testing done:**

Built an `aws-dev` variant with my changes and tested that changes to the host-containers settings behaved as expected. The admin container started with my provided user data, and I was able to add a new test host container.

TODO: test that the migrations behave as expected

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2024-02-14 23:33 UTC, sam-berning commented
^ update template to `{{{` everything to keep it consistent with what we expected when reading directly from the API

2024-02-15 17:16 UTC, webern approved these changes

2024-02-15 17:16 UTC, webern commented on sources/api/host-containers/src/config.rs
> +#[model]
Using  `model` makes me a little squeamish, perhaps irrationally. What is it that this macro is doing for you? Is it just turning the fields into `Options` and implementing `Deserialize`? If so, I would prefer that be explicitly done rather than hiding information from the programmer in a fairly anemic procedural macro.

I feel the same way about `modeled-types` just due to its associate the "The Model", however I see that you are using `ValidBase64` which is real/desirable code re-use.

2024-02-15 17:16 UTC, webern commented on packages/os/os.spec
> +%{_cross_templatedir}/host-containers-toml
These config file names are a little bit confusing next to each other, but I think you've named the new one correctly.

2024-02-15 17:16 UTC, webern commented on sources/api/host-containers/Cargo.toml
> -models = { path = "../../models", version = "0.1" }
:tada:

2024-02-15 17:16 UTC, webern commented on sources/api/host-containers/src/main.rs
> +fn get_host_containers<P>(config_path: P) -> Result<HashMap<Identifier, config::HostContainer>>
Can you add a test for this function by creating a config file, perhaps inline? One benefit of the new paradigm is that we can test since we don't need the API server.

2024-02-15 17:16 UTC, webern commented on sources/api/host-containers/src/main.rs
> +    let config_path = config_path.as_ref();
More information is better when debugging.

```suggestion
    let config_path = config_path.as_ref();
    debug!("Reading containers from the config file: {}", config_path.display());
```

2024-02-15 17:16 UTC, webern commented on sources/api/host-containers/src/main.rs
> -async fn run() -> Result<()> {
:tada:

2024-02-15 19:58 UTC, sam-berning commented on sources/api/host-containers/src/config.rs
> +#[model]
> Is it just turning the fields into Options and implementing Deserialize?

Yeah, this and making the struct and all fields `pub`. I was also implementing `Debug` during development but it's not necessary. I think you're right that we shouldn't use `model-derive` here, I just noticed that it did all of what I wanted and it looked prettier 😆

2024-02-15 20:35 UTC, sam-berning commented on packages/os/os.spec
> +%{_cross_templatedir}/host-containers-toml
yeah agreed. I also considered combining the two config files but I think that would be even more confusing

2024-02-15 22:42 UTC, webern commented on sources/api/host-containers/src/config.rs
> +#[model]
Prettier is all relative. To me, knowing that something is `pub` without looking at a derive macro is... prettier.

2024-02-15 22:49 UTC, sam-berning commented
^ address @webern's comments

2024-02-16 22:37 UTC, jmt-lab approved these changes

2024-02-16 23:55 UTC, webern approved these changes

2024-03-05 01:04 UTC, webern requested changes
Switching my review status as it needs a rebase and then needs testing. Here is the test plan that we have suggested, this should be pasted into the testing section of the PR description

```
- [ ] Ran `cargo +nightly udeps` to ensure all unused dependencies have been removed
- [ ] Pass the settings on first boot via userdata. Verify config.
- [ ] cat /etc/os-release record your build ID include commit sha, record this
- [ ] Use apiclient to update relevant settings at runtime. Verify config was updated correctly.
- [ ] Downgrade to older version. 
  - [ ] verify connectivity
  - [ ] cat /etc/os-release to verify lower version
  - [ ] verify that migrations have changed the metadata/settings as expected (i.e. they are gone from the datastore, or lists have been changed back)
- [ ] Upgrade to newer version.
  - [ ] verify connectivity
  - [ ] cat /etc/os-release to verify version
  - [ ] verify config file
 ```

2024-03-06 02:01 UTC, sam-berning commented
^ testing summary:

- [x] Ran `cargo +nightly udeps` to ensure all unused dependencies have been removed
- [x] Pass the settings on first boot via userdata. Verify config.

    Enabled and configured the admin container in user data. `cat`'d the config file at `/etc/host-containers/host-containers.toml` and it contained the user data.

- [x] cat /etc/os-release record your build ID include commit sha, record this

```
bash-5.1# cat /etc/os-release
...
VERSION="1.19.3 (aws-dev)"
...
BUILD_ID=1e9e8f3a
...
```

- [x] Use apiclient to update relevant settings at runtime. Verify config was updated correctly.

```
bash-5.1# apiclient set --json '{"settings": {"host-containers": {"foo": {"source": "public.ecr.aws/bottlerocket/bottlerocket-admin:v0.11.5", "enabled": true, "superpowered": true}}}}'
bash-5.1# cat /etc/host-containers/host-containers.toml
...
[host-containers."foo"]
source = "public.ecr.aws/bottlerocket/bottlerocket-admin:v0.11.5"
enabled = true
superpowered = true
```

- [x] Downgrade to older version.
  - [x] verify connectivity
  - [x] cat /etc/os-release to verify lower version
  - [x] verify that migrations have changed the metadata/settings as expected (i.e. they are gone from the datastore, or lists have been changed back)

```
bash-5.1# updog update -i 1.19.2 -r -n
Starting update to 1.19.2
Reboot scheduled for Wed 2024-03-06 01:53:29 UTC, use 'shutdown -c' to cancel.
Update applied: aws-dev 1.19.2
# after reboot, was able to ssh successfully
bash-5.1# cat /etc/os-release
...
VERSION="1.19.2 (aws-dev)"
...
# no host-containers-toml config file, and it is removed from host-containers config files
bash-5.1# ls /var/lib/bottlerocket/datastore/current/live/configuration-files/ 
certdog-toml   containerd-config-toml  hostname				   metricdog-toml  motd		proxy-env
cfsignal-toml  docker-daemon-config    hosts				   modprobe-conf   netdog-toml	updog-toml
chrony-conf    host-ctr-toml	       log4j-hotpatch-enabled-log-message  modules-load    oci-hooks
bash-5.1# cat /var/lib/bottlerocket/datastore/current/live/services/host-containers/configuration-files 
["host-ctr-toml"]
```

- [x] Upgrade to newer version.
  - [x] verify connectivity
  - [x] cat /etc/os-release to verify version
  - [x] verify config file

```
bash-5.1# updog update -i 1.19.3 -r -n
Starting update to 1.19.3
Reboot scheduled for Wed 2024-03-06 01:58:04 UTC, use 'shutdown -c' to cancel.
Update applied: aws-dev 1.19.3
# after reboot, was able to ssh successfully
bash-5.1# cat /etc/os-release
...
VERSION="1.19.3 (aws-dev)"
...
bash-5.1# cat /etc/host-containers/host-containers.toml
# looked as expected!
```

2024-03-06 18:41 UTC, webern approved these changes
Looks good.

2024-03-06 20:15 UTC, jmt-lab commented
Looks good to me as well

2024-03-06 21:27 UTC, merged