Revert "packages: update libnvidia-container to 1.14.5"
bottlerocket-os/bottlerocket pull request #3854
Opened 2024-03-25 22:06 UTC by gthao313

This reverts commit 60b95c39234cc1cedd0c813114f0da39b318fcdc.

**Issue number:**

Closes #

**Description of changes:**
During 1.19.3 release, aarch64-aws-ecs-1-nvidia and aarch64-aws-ecs-2-nvidia failed on workload tests consistently.
We have confirmed the commit 60b95c39234cc1cedd0c813114f0da39b318fcdc makes the ecs-2-nvidia and ecs-1-nvidia test fail. Revert to solve the issue and unblock the release.

**Testing done:**
@vyaghras and @arnaldo2792 completed the and confirmed the AMI without this commit worked as expected.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2024-03-25 22:20 UTC, vyaghras commented
We will need to revert all 3 commits: 
- https://github.com/bottlerocket-os/bottlerocket/pull/3815/commits/9b661d1a81b56a444d058df29af8140b50dfe6ee, 
- https://github.com/bottlerocket-os/bottlerocket/pull/3815/commits/f9c06447564f846ef574d74da17e7017a20883a1, 
- https://github.com/bottlerocket-os/bottlerocket/pull/3815/commits/60b95c39234cc1cedd0c813114f0da39b318fcdc

2024-03-25 23:08 UTC, vyaghras approved these changes

2024-03-25 23:40 UTC, jpculp requested changes
I think I would change the title of the commit to `Revert "Update Lib Nvidia container package"` and then have the 3 commits in the details.

2024-03-25 23:47 UTC, jpculp approved these changes

2024-03-26 00:38 UTC, rpkelly approved these changes

2024-03-26 03:32 UTC, arnaldo2792 approved these changes

2024-03-26 03:32 UTC, arnaldo2792 reviewed
As requested offline, lets create three different commits

2024-03-26 17:18 UTC, vyaghras approved these changes

2024-03-26 17:26 UTC, jpculp approved these changes

2024-03-26 17:28 UTC, merged