1.20.x: kernel updates, statically linked modprobe
bottlerocket-os/bottlerocket pull request #3997
Opened 2024-05-28 19:00 UTC by larvacea

**Description of changes:**

* Update kernels to 6.1.90, 5.15.158, and 5.10.216 ([#3976], [#3972])
* Include statically-linked packages/kmod modprobe ([#3981])

**Testing done:**

Kernel changes: our standard sonobuoy tests and manual inspection of patch and configuration changes.
modprobe: see [#3981] for details.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2024-05-28 19:25 UTC, yeazelm approved these changes

2024-05-28 19:50 UTC, ginglis13 requested changes

2024-05-28 19:50 UTC, ginglis13 commented on CHANGELOG.md
> +
```suggestion

[#3972]: https://github.com/bottlerocket-os/bottlerocket/pull/3972
[#3976]: https://github.com/bottlerocket-os/bottlerocket/pull/3976
[#3981]: https://github.com/bottlerocket-os/bottlerocket/pull/3981

```

2024-05-28 19:50 UTC, ginglis13 commented on CHANGELOG.md
> +* Include statically-linked packages/kmod ([#3981])
```suggestion
* Include statically linked version of kmod ([#3981])
```

2024-05-28 21:08 UTC, larvacea commented
I have incorporated @ginglis13's suggested changes.

2024-05-28 21:48 UTC, ginglis13 approved these changes

2024-05-28 21:49 UTC, merged

2024-06-03 10:09 UTC, obirhuppertz commented
Would it be possible to publish a 1.20.1 release with just these changes so we can select this AMI in our launch template? Reading through the merged issues, cilium should be working again with these commits.

Thanks @vigh-m (and any unmentioned contributor) for investigating and fixing this issue!

2024-06-14 03:38 UTC, yeazelm commented
Hello @obirhuppertz, we did release [1.20.2](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.20.2) which provides a fix for CIlium. Please check that release and follow up on https://github.com/bottlerocket-os/bottlerocket/issues/3968 if you experience more issues with Cilium. Thanks!

2024-06-14 10:27 UTC, obirhuppertz commented
@yeazelm @vigh-m can confirm cilium is still working on 1.20.2 bottlerocket nodes having the workaround via extraMounts and volumes removed in values.yaml. For me the issue is fixed now. Great work! :partying_face: