twoliter: update twoliter to v0.2.0
bottlerocket-os/bottlerocket pull request #4008
Opened 2024-05-30 14:37 UTC by sumukhballal

**Issue number:**

Closes #

**Description of changes:**

Updates twoliter to version v0.2.0 and Twoliter.toml to new specification.

**Testing done:**
- [ ] Build a variant of Bottlerocket.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

2024-05-30 18:11 UTC, sumukhballal commented
Updated Twoliter version to v0.2.0-rc2 and added @webern 's [commit](https://github.com/bottlerocket-os/bottlerocket/pull/3962/commits/c7f1177f79d8ac3ac44d6228c1115f8a3997f213
)

2024-05-31 00:44 UTC, jpculp approved these changes

2024-05-31 01:49 UTC, jpculp commented
Using `v0.2.0-rc3` I was able to build, boot, and repack `aws-k8s-1.28`.

2024-05-31 01:57 UTC, jpculp commented
Also built and booted `aws-ecs-2`.

2024-05-31 12:32 UTC, webern requested changes
Looks good! Blocking for the final Twoliter tag only.

2024-05-31 12:32 UTC, webern commented on Makefile.toml
> +TWOLITER_VERSION = "v0.2.0-rc3"
```suggestion
TWOLITER_VERSION = "v0.2.0"
```

2024-05-31 15:28 UTC, sumukhballal commented
Updated twoliter version to v0.2.0

2024-05-31 16:31 UTC, webern approved these changes

2024-05-31 16:34 UTC, merged